on: push
name: Deploy
jobs:
  web-deploy:
    name: ğŸ‰ Backend bereitstellen
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Aktuellen Code abrufen
      uses: actions/checkout@v2.3.2
    
    - name: ğŸ“‚ Dateien synchronisieren
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}